apiVersion: v1
kind: Namespace
metadata:
  name: dev-service


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-deployment
  namespace: dev-service
  labels:
    app: http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http
  template:
    metadata:
      labels:
        app: http
    spec:
      containers:
      - name: http
        image: docker.io/vikkyomkar/http_service:v1.0
        ports:
         - containerPort: 8080
        env:
         - name: SERVE_PORT
           value: "8080"
        resources:
           limits:
             memory: 100Mi
             
---

apiVersion: v1
kind: Service
metadata:
  namespace: dev-service
  name: http-lb-service
spec:
  type: LoadBalancer
  selector:
    app: http
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
